// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using WorldLine.Api.Data;

#nullable disable

namespace WorldLine.Api.Migrations
{
    [DbContext(typeof(WorldLineDbContext))]
    [Migration("20260827031210_AddRegimeTransitionEvents")]
    partial class AddRegimeTransitionEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldLine.Api.Data.Entities.EventTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tag_name");

                    b.HasKey("Id")
                        .HasName("pk_event_tags");

                    b.HasIndex("TagName")
                        .IsUnique()
                        .HasDatabaseName("ix_event_tags_tag_name");

                    b.ToTable("event_tags", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("EndDecimal")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("end_decimal");

                    b.Property<string>("EndEdtf")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("end_edtf");

                    b.Property<MultiPolygon>("InfluenceArea")
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("influence_area");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Point>("OriginPoint")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("origin_point");

                    b.Property<string>("ParentEventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parent_event_id");

                    b.Property<MultiLineString>("Routes")
                        .HasColumnType("geometry(MultiLineString,4326)")
                        .HasColumnName("routes");

                    b.Property<string>("Sections")
                        .HasColumnType("jsonb")
                        .HasColumnName("sections");

                    b.Property<decimal>("StartDecimal")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("start_decimal");

                    b.Property<string>("StartEdtf")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("start_edtf");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_historical_events");

                    b.HasIndex("ParentEventId")
                        .HasDatabaseName("ix_historical_events_parent_event_id");

                    b.ToTable("historical_events", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEventControversy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("NeutralDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neutral_description");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("topic");

                    b.Property<string>("Viewpoints")
                        .HasColumnType("jsonb")
                        .HasColumnName("viewpoints");

                    b.HasKey("Id")
                        .HasName("pk_historical_event_controversies");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_historical_event_controversies_event_id");

                    b.ToTable("historical_event_controversies", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEventPerspective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClaimedCasualties")
                        .HasColumnType("jsonb")
                        .HasColumnName("claimed_casualties");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("local_name");

                    b.Property<string>("NarrativeSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narrative_summary");

                    b.Property<int?>("ObserverCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("observer_category_id");

                    b.Property<string>("OfficialJustification")
                        .HasColumnType("text")
                        .HasColumnName("official_justification");

                    b.Property<string>("PrimarySources")
                        .HasColumnType("jsonb")
                        .HasColumnName("primary_sources");

                    b.Property<Guid?>("RegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_id");

                    b.HasKey("Id")
                        .HasName("pk_historical_event_perspectives");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_historical_event_perspectives_event_id");

                    b.HasIndex("ObserverCategoryId")
                        .HasDatabaseName("ix_historical_event_perspectives_observer_category_id");

                    b.HasIndex("RegimeId")
                        .HasDatabaseName("ix_historical_event_perspectives_regime_id");

                    b.ToTable("historical_event_perspectives", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEventTagMap", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("EventId", "TagId")
                        .HasName("pk_historical_event_tag_map");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_historical_event_tag_map_tag_id");

                    b.ToTable("historical_event_tag_map", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.LineagePreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("preset_name");

                    b.HasKey("Id")
                        .HasName("pk_lineage_presets");

                    b.ToTable("lineage_presets", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.LineagePresetMember", b =>
                {
                    b.Property<Guid>("PresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("preset_id");

                    b.Property<Guid>("RegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("PresetId", "RegimeId")
                        .HasName("pk_lineage_preset_members");

                    b.HasIndex("RegimeId")
                        .HasDatabaseName("ix_lineage_preset_members_regime_id");

                    b.ToTable("lineage_preset_members", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.ObserverCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_name");

                    b.HasKey("Id")
                        .HasName("pk_observer_categories");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("ix_observer_categories_category_name");

                    b.ToTable("observer_categories", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.PlaceName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<string>("HistoricalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("historical_name");

                    b.Property<string>("ModernName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("modern_name");

                    b.Property<NpgsqlRange<int>?>("ValidPeriod")
                        .HasColumnType("int4range")
                        .HasColumnName("valid_period");

                    b.HasKey("Id")
                        .HasName("pk_place_names");

                    b.ToTable("place_names", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.Regime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DestroyedByRegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("destroyed_by_regime_id");

                    b.Property<string>("OriginTransitionType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("origin_transition_type");

                    b.Property<Guid?>("PredecessorRegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("predecessor_regime_id");

                    b.Property<string>("SelfName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("self_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_regimes");

                    b.HasIndex("DestroyedByRegimeId")
                        .HasDatabaseName("ix_regimes_destroyed_by_regime_id");

                    b.HasIndex("PredecessorRegimeId")
                        .HasDatabaseName("ix_regimes_predecessor_regime_id");

                    b.ToTable("regimes", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alias_name");

                    b.Property<string>("AliasType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alias_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ObserverRegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("observer_regime_id");

                    b.Property<Guid>("RegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_id");

                    b.HasKey("Id")
                        .HasName("pk_regime_aliases");

                    b.HasIndex("ObserverRegimeId")
                        .HasDatabaseName("ix_regime_aliases_observer_regime_id");

                    b.HasIndex("RegimeId")
                        .HasDatabaseName("ix_regime_aliases_regime_id");

                    b.ToTable("regime_aliases", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("RegimeAId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_a_id");

                    b.Property<Guid>("RegimeBId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_b_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relation_type");

                    b.Property<MultiLineString>("Route")
                        .HasColumnType("geometry(MultiLineString,4326)")
                        .HasColumnName("route");

                    b.Property<NpgsqlRange<int>>("ValidPeriod")
                        .HasColumnType("int4range")
                        .HasColumnName("valid_period");

                    b.HasKey("Id")
                        .HasName("pk_regime_relations");

                    b.HasIndex("RegimeAId")
                        .HasDatabaseName("ix_regime_relations_regime_a_id");

                    b.HasIndex("RegimeBId")
                        .HasDatabaseName("ix_regime_relations_regime_b_id");

                    b.ToTable("regime_relations", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeTerritory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CorrectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_at");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("text")
                        .HasColumnName("correction_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<MultiPolygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsDisputed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disputed");

                    b.Property<Guid>("RegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_id");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by");

                    b.Property<NpgsqlRange<int>>("ValidPeriod")
                        .HasColumnType("int4range")
                        .HasColumnName("valid_period");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_regime_territories");

                    b.HasIndex("RegimeId")
                        .HasDatabaseName("ix_regime_territories_regime_id");

                    b.HasIndex("SupersededBy")
                        .HasDatabaseName("ix_regime_territories_superseded_by");

                    b.ToTable("regime_territories", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeTransitionEvent", b =>
                {
                    b.Property<Guid>("RegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_id");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("TransitionKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("transition_kind");

                    b.HasKey("RegimeId", "EventId", "TransitionKind")
                        .HasName("pk_regime_transition_events");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_regime_transition_events_event_id");

                    b.ToTable("regime_transition_events", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.ReignEra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<string>("EraName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("era_name");

                    b.Property<Guid>("RegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("regime_id");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_reign_eras");

                    b.HasIndex("RegimeId")
                        .HasDatabaseName("ix_reign_eras_regime_id");

                    b.ToTable("reign_eras", (string)null);
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEvent", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.HistoricalEvent", null)
                        .WithMany()
                        .HasForeignKey("ParentEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_historical_events_historical_events_parent_event_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEventControversy", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.HistoricalEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_historical_event_controversies_historical_events_event_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEventPerspective", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.HistoricalEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_historical_event_perspectives_historical_events_event_id");

                    b.HasOne("WorldLine.Api.Data.Entities.ObserverCategory", null)
                        .WithMany()
                        .HasForeignKey("ObserverCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_historical_event_perspectives_observer_categories_observer_");

                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_historical_event_perspectives_regimes_regime_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.HistoricalEventTagMap", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.HistoricalEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historical_event_tag_map_historical_events_event_id");

                    b.HasOne("WorldLine.Api.Data.Entities.EventTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historical_event_tag_map_event_tags_tag_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.LineagePresetMember", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.LineagePreset", null)
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineage_preset_members_lineage_presets_preset_id");

                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lineage_preset_members_regimes_regime_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.Regime", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("DestroyedByRegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_regimes_regimes_destroyed_by_regime_id");

                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("PredecessorRegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_regimes_regimes_predecessor_regime_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeAlias", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("ObserverRegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_regime_aliases_regimes_observer_regime_id");

                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_regime_aliases_regimes_regime_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeRelation", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_regime_relations_regimes_regime_a_id");

                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_regime_relations_regimes_regime_b_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeTerritory", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_regime_territories_regimes_regime_id");

                    b.HasOne("WorldLine.Api.Data.Entities.RegimeTerritory", null)
                        .WithMany()
                        .HasForeignKey("SupersededBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_regime_territories_regime_territories_superseded_by");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.RegimeTransitionEvent", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.HistoricalEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regime_transition_events_historical_events_event_id");

                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regime_transition_events_regimes_regime_id");
                });

            modelBuilder.Entity("WorldLine.Api.Data.Entities.ReignEra", b =>
                {
                    b.HasOne("WorldLine.Api.Data.Entities.Regime", null)
                        .WithMany()
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reign_eras_regimes_regime_id");
                });
#pragma warning restore 612, 618
        }
    }
}
